### ISSUE TITLE
Bug related to issue #56 - AttributeError: 'numpy.float32' object has no attribute 'is_integer'

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#67]
**BUG 1 – Something wrong with filling the dataframe. Would try another method than `df.loc[variable, “pop”] = gadm_pop` to test if there is somehow the bug.**

(toast) max@max-XPS-13-9300:~/OneDrive/PHD-Flexibility/07_pypsa-africa/0github/pypsa-africa/pypsa-africa$ /home/max/anaconda3/envs/toast/bin/python /home/max/OneDrive/PHD-Flexibility/07_pypsa-africa/0github/pypsa-africa/pypsa-africa/scripts/build_shapes.py
This is the repository path:  /home/max/OneDrive/PHD-Flexibility/07_pypsa-africa/0github/pypsa-africa/pypsa-africa/scripts
Had to go 0 folder(s) up.
Create country shapes
/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/geopandas/geodataframe.py:577: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
  for feature in features_lst:
Create offshore shapes
/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/geopandas/geodataframe.py:577: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
  for feature in features_lst:
Merge country shapes
Creation GADM GeoDataFrame
/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/geopandas/geodataframe.py:577: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
  for feature in features_lst:
Add population data to GADM GeoDataFrame
Download WorldPop datasets
DZ :  0  out of  1504
103142.46 (PRINT BY MAX. To check the population data)
Traceback (most recent call last):
  File "/home/max/OneDrive/PHD-Flexibility/07_pypsa-africa/0github/pypsa-africa/pypsa-africa/scripts/build_shapes.py", line 574, in <module>
    gadm_shapes = gadm(layer_id, update, out_logging, year)
  File "/home/max/OneDrive/PHD-Flexibility/07_pypsa-africa/0github/pypsa-africa/pypsa-africa/scripts/build_shapes.py", line 529, in gadm
    add_population_data(df_gadm, countries, year, update, out_logging)
  File "/home/max/OneDrive/PHD-Flexibility/07_pypsa-africa/0github/pypsa-africa/pypsa-africa/scripts/build_shapes.py", line 383, in add_population_data
    df_gadm.loc[index, "pop"] = pop_by_geom
  File "/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/pandas/core/indexing.py", line 723, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/pandas/core/indexing.py", line 1730, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/pandas/core/indexing.py", line 1817, in _setitem_with_indexer_split_path
    self._setitem_single_column(loc, value, pi)
  File "/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/pandas/core/indexing.py", line 1920, in _setitem_single_column
    ser._mgr = ser._mgr.setitem(indexer=(pi,), value=value)
  File "/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 355, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 926, in setitem
    if not self._can_hold_element(value):
  File "/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 622, in _can_hold_element
    return can_hold_element(self.values, element)
  File "/home/max/anaconda3/envs/toast/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 2192, in can_hold_element
    if is_float(element) and element.is_integer():
AttributeError: 'numpy.float32' object has no attribute 'is_integer'

**Comment by pz-max** [comment]
Let's chat tomorrow/today about that

**Comment by pz-max** [comment]
solved. Had an issue with anaconda
